apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ocwaStorageApi.fullname" . }}-secrets
  labels:
    app: {{ template "ocwaStorageApi.name" . }}
    chart: {{ template "ocwaStorageApi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  access_key: {{ .Values.access_key | b64enc }}
  access_secret: {{ .Values.access_secret | b64enc }}
  jwt_secret: {{ .Values.jwtSecret | b64enc }}
  jwt_aud: {{ .Values.jwtAud | b64enc }}