{{- if .Values.downloadIngress.enabled -}}
{{- $fullName := include "ocwaFrontend.fullname" . -}}
{{- $ingressPath := .Values.downloadIngress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-download
  labels:
    app: {{ template "ocwaFrontend.name" . }}
    chart: {{ template "ocwaFrontend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.downloadIngress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.downloadIngress.tls }}
  tls:
  {{- range .Values.downloadIngress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{ range $i, $host := .Values.downloadIngress.hosts }}
    - host: {{ $host.name }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $host.service }}
              servicePort: {{ $host.port }}
  {{- end }}
{{- end }}
