apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ocwaForumApi.fullname" . }}-secrets
  labels:
    app: {{ template "ocwaForumApi.name" . }}
    chart: {{ template "ocwaForumApi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  jwtSecret: {{ .Values.jwtSecret | b64enc }}
  dbPassword: {{ .Values.database.password | b64enc }}